export const postList = [
  {
    id: "1",
    image: "/images/gallery/1.jpg",
    avatar: "/images/user.jpg",
    user: "Evelyn T.",
    prof: "Director",
    views: 522,
    price: 99,
    link: "https://www.google.com/",
    title: "In collaboration with Valeriia Mille",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry Ipsum has been.",
  },
  {
    id: "2",
    image: "/images/gallery/2.jpg",
    avatar: "/images/user.jpg",
    user: "Evelyn T.",
    prof: "Director",
    views: 522,
    price: 99,
    link: "https://www.google.com/",
    title: "In collaboration with Valeriia Mille",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry Ipsum has been.",
  },
  {
    id: "3",
    image: "/images/gallery/3.jpg",
    avatar: "/images/user.jpg",
    user: "Evelyn T.",
    prof: "Director",
    views: 522,
    price: 99,
    link: "https://www.google.com/",
    title: "In collaboration with Valeriia Mille",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry Ipsum has been.",
  },
  {
    id: "4",
    image: "/images/gallery/4.jpg",
    avatar: "/images/user.jpg",
    user: "Evelyn T.",
    prof: "Director",
    views: 522,
    price: 99,
    link: "https://www.google.com/",
    title: "In collaboration with Valeriia Mille",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry Ipsum has been.",
  },
  {
    id: "5",
    image: "/images/gallery/5.jpg",
    avatar: "/images/user.jpg",
    user: "Evelyn T.",
    prof: "Director",
    views: 522,
    price: 99,
    link: "https://www.google.com/",
    title: "In collaboration with Valeriia Mille",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry Ipsum has been.",
  },
  {
    id: "6",
    image: "/images/gallery/6.jpg",
    avatar: "/images/user.jpg",
    user: "Evelyn T.",
    prof: "Director",
    views: 522,
    price: 99,
    link: "https://www.google.com/",
    title: "In collaboration with Valeriia Mille",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry Ipsum has been.",
  },
];
